### ISSUE TITLE
Request: Support for UltraWide Monitor

### ISSUE THREAD

**Issue by jsanzdev** [workspacer/workspacer#107]
When using an ultrawide monitor, the windows layout it gets weird as the right part tends to get long and short on height, making this impossible to work with.

My screen is Dual FULLHD

Would it be possible to create a layout to divide the screen into 3 to 4 horizontal zones and then you can split each zone into two vertically?

This could be dynamic: If you open two applications your screen is split into two horizontally (as per now) a third application makes another division horizontally the fourth application could be opened below the third division, or making the fourth division horizontally.

Would it be possible to choose how many divisions you can do through the config file?

**Comment by N1x0** [comment]
Hi @Grefusa ,
have you tried using the `VertLayoutEngine` or have only tried out the one of the two defaults (`tall` & `full`)?

If you haven't tried it yet then might I suggest you give that a shot. I think this might get you at least to a usable setup.
Here a snippet:
``` csharp
var sticky = new StickyWorkspaceContainer(context, StickyWorkspaceIndexMode.Local);
context.WorkspaceContainer = sticky; 

sticky.CreateWorkspace("Vertical Layout", new VertLayoutEngine());

``

**Comment by Grefusa** [comment]
Thank you for this, I will give it a try!
