### ISSUE TITLE
With sticky monitor conf, restarting workspacer moves windows around

### ISSUE THREAD

**Issue by sim590** [workspacer/workspacer#108]
In my config, I have the following:

```cs
  var monitors = context.MonitorContainer.GetAllMonitors();
  var sticky   = new StickyWorkspaceContainer(context, StickyWorkspaceIndexMode.Local);
  context.WorkspaceContainer = sticky;
  for (int i = 0; i < monitors.Length; i++) {
    int j1 = i+1;
    sticky.CreateWorkspaces(monitors[i], j1 + ":1", j1 + ":2", j1 + ":3", j1 + ":4", j1 + ":5", j1 + ":6", j1 + ":7", j1 + ":8", j1 + ":9");
  }
```

Each time I restart Workspacer, some windows move around in workspaces. For instance, I may have two windows on the second tag of the second monitor (`2:2`). When restarting, the two windows may move on the 7th tag. The movement seems arbitrary. However, what is consistent is that the focused tag will always move to the first tag. So if you're focusing a window on third tag (`2:3`), then after restart, the window is going to be on tag `2:1`.

Why is that? Is that a bug or something with my config? In any case, I think that Workspacer should prevent this whatever the config of the user...

**Comment by sim590** [comment]
If I change the above snippet to:

```cs
  var monitors = context.MonitorContainer.GetAllMonitors();
  if (monitors.Length == 1) {
    context.WorkspaceContainer.CreateWorkspaces("1", "2", "3", "4", "5", "6", "7", "8", "9");
  } else {
    var sticky = new StickyWorkspaceContainer(context, StickyWorkspaceIndexMode.Local);
    context.WorkspaceContainer = sticky;
    for (int i = 0; i < monitors.Length; i++) {
      int j1 = i+1;
      sticky.CreateWorkspaces(monitors[i], j1 + ":1", j1 + ":2", j1 + ":3", j1 + ":4", j1 + ":5", j1 + ":6", j1 + ":7", j1 + ":8", j1 + ":9");
    }
  }
```

I don't get the issue on a single monitor setting.

**Comment by N1x0** [comment]
I believe PR #183 fixed the issue. If you could quickly test it as well we can close this one.

**Comment by sim590** [comment]
Thanks! I can now use multiple monitors with Workspacer!!!
