### ISSUE TITLE
CS1660 error in default configuration

### ISSUE THREAD

**Issue by imswebra** [workspacer/workspacer#109]
Not new to programming, but new to C# and .NET. I've installed the VSCode [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp), and the .NET Core 3.1 SDK as recommended.

When opening the default configuration, I get a `Cannot convert lambda expression to type 'Action<IConfigContext>' because it is not a delegate type [workspacer.config.csx]` error message (CS1660) on line 12 (the `doConfig` assignment).

I find a type conversion error curious on a fresh install of .NET Core, but perhaps I am missing a dependency of some sort. Is this my setup or is there a legitimate error?

**Comment by o0morgan0o** [comment]
Same problem for me for the sticky configuration on the line 
```
var defaultLayouts = () => bar.WrapLayouts(new TallLayoutEngine(), new FullLayoutEngine());
```

**Comment by AlexN34** [comment]
I also ran into this with the default config.
Running it seems fine still but VSCode's linting just seems to not like trying to cast the whole `doConfig` lambda as an `Action<IConfigContext>`.  
Running the `.csx` manually with `dotnet-script` works fine as well, could be a funny thing about how `omnisharp` etc works script mode.

I made a change as a workaround to stop the whole lambda being highlighted in angry red. While I couldn't get rid of it altogether, modifying it to this made the linting problem about creating the Action instead (which gives me the problem away from the main configuration at least 🤷‍♂️ )

```
static void doConfig(IConfigContext context)
{
    context.AddBar();
    context.AddFocusIndicator();
    var actionMenu = context.AddActionMenu();
    context.WorkspaceContainer.CreateWorkspaces("one", "two", "three", "four", "anothercustom");
}

return new Action<IConfigContext>(doConfig);

```
(Would be keen to know of a true fix if it exists, though!)

**Comment by BeeryShklar** [comment]
You can just wrap the arrow function in `new Action<IConfigContext>()` like that:
```c#
Action<IConfigContext> doConfig = new Action<IConfigContext>((context) => {
  // ...
});
return doConfig;
```

And for other arrow functions you can do this:
```c#
new Func<return_type>(() =>
  // ...
)
```

**Comment by josteink** [comment]
If you have any concrete examples of how the documentation is wrong, I would strongly encourage sending a PR with corrections.

It's not hard and they will most likely be accepted quite quickly :smiley:

**Comment by BeeryShklar** [comment]
It would probably be better to just fix the problem instead of changing the documentation.
I also don't really know c#, just good enough to search google and find the answers.
