### ISSUE TITLE
Github Code Snippets out of date

### ISSUE THREAD

**Issue by N1x0** [workspacer/workspacer#111]
All the snippets provided on github are very much out of date and don't work. These should either be updated or completely removed as the updated ones are  available on the website.
If you'd still like to have them on Github I'll make a PR for with the current implementation

**Comment by josteink** [comment]
Hey there and thanks for reporting in.

I think having snippets there is definitely helpful, but not if out of date.

If you're willing to update them, I'm willing to merge :+1:

**Comment by N1x0** [comment]
Alright working on it now, will submit a PR over the weekend once I've figured out some of the quirks.
