### ISSUE TITLE
Really confused, would love some help how to configure this, tried changing the menubar without any success. 

### ISSUE THREAD

**Issue by TobiasDev** [workspacer/workspacer#113]
Hello,

I'm wondering if someone could help me with some examples, because I'm super confused about how to work with my config file.

I tried to change the AddBar one with the example in the snippets, like this: 

```
using System;
using workspacer;
using workspacer.Bar;
using workspacer.ActionMenu;
using workspacer.FocusIndicator;

Action<IConfigContext> doConfig = (context) =>
{
    var bar = context.AddBar(new BarPluginConfig()
    {
        BarTitle = "workspacer.Bar",
        BarHeight = 50,
        FontSize = 16,
        DefaultWidgetForeground = Color.White,
        DefaultWidgetBackground = Color.Black,
        Background = Color.Black,
        LeftWidgets = () => new IBarWidget[] { new WorkspaceWidget(), new TextWidget(": "), new TitleWidget() },
        RightWidgets = () => new IBarWidget[] { new TimeWidget(), new ActiveLayoutWidget() },
    });
    context.AddFocusIndicator();
    var actionMenu = context.AddActionMenu();

    context.WorkspaceContainer.CreateWorkspaces("one", "two", "three", "four", "five");

};
return doConfig;
```

However, all that happens is that workspaces crashes. :(

I'm also wondering if there is any kind of configuration I could do to remove these pretty large gaps between my software? 
![grafik](https://user-images.githubusercontent.com/5912371/88783854-9b0bed00-d18f-11ea-870f-c47d2b2f3271.png)

I would love if someone have an example of their config, just so I can understand what I need to change and work with to get it working! Because the one thing I really miss when I have to use Windows (at work), is a proper tiling window manager like this! So to be able to configure this would be amazing!

**Comment by N1x0** [comment]
Hi there,

So for a sample config I will share you the one I setup since discovering it on the weekend. I totally agree that the documentation is very lacking. Regarding the snippets I actually made an issue #111 about this being lacking and I will setup a PR to update those once I have everything figured out myself over the weekend.
I've added the screenshot to highlight the impact of color changes on the bar. Let me know if you have any questions, happy to help as well (if I can).

![bar](https://user-images.githubusercontent.com/47623143/88823714-98d97b00-d1ef-11ea-8818-809568e419b7.png)


```csharp
#r "C:\Program Files\workspacer\workspacer.Shared.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.Bar\workspacer.Bar.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.ActionMenu\workspacer.ActionMenu.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.FocusIndicator\workspacer.FocusIndicator.dll"

using System;
using System.IO;
using workspacer;
using workspacer.Bar;
using workspacer.ActionMenu;
using workspacer.FocusIndicator;

Action<IConfigContext> doConfig = (context) => {
    
context.AddBar(new BarPluginConfig(){
    BarTitle = "workspacer.Bar",
    BarHeight = 20,
    FontSize = 12,
    FontName = "Font Awesome",
    DefaultWidgetForeground = Color.Blue,
    DefaultWidgetBackground = Color.White,
    Background = Color.White,
});

context.AddFocusIndicator(new FocusIndicatorPluginConfig(){
    BorderColor = Color.Lime,
    TimeToShow = 150,
});

    var actionMenu = context.AddActionMenu(new ActionMenuPluginConfig(){
        Foreground = Color.Blue,
    });

    var sticky = new StickyWorkspaceContainer(context, StickyWorkspaceIndexMode.Local);
    context.WorkspaceContainer = sticky;

    // workspaces and layouts
    sticky.CreateWorkspaces("Chat", "Web", "Working","Code", "Games", "Music", "Email");
    context.WindowRouter.AddRoute((window) => window.Title.Contains("Outlook") ? context.WorkspaceContainer["Email"] : null);
    context.WindowRouter.AddRoute((window) => window.Title.Contains("Visual Studio") ? context.WorkspaceContainer["Code"] : null);
    context.WindowRouter.AddRoute((window) => window.Title.Contains("PowerShell") ? context.WorkspaceContainer["Code"] : null);
    context.WindowRouter.AddRoute((window) => window.Title.Contains("Spotify") ? context.WorkspaceContainer["Music"] : null);
    context.WindowRouter.AddRoute((window) => window.Title.Contains("Firefox") ? context.WorkspaceContainer["Web"] : null);
    // filters
    context.WindowRouter.AddFilter((window) => !window.Title.Contains("Dota 2"));        

    // keybinds
     var mod = KeyModifiers.Alt;
    context.Keybinds.Subscribe(mod, Keys.F, () => System.Diagnostics.Process.Start("explorer.exe", @"C:\Users\Desktop"));
    context.Keybinds.Subscribe(mod, Keys.B, () => System.Diagnostics.Process.Start(@"C:\Program Files\Mozilla Firefox\firefox.exe"));

};

return doConfig;
```

**Comment by TobiasDev** [comment]
That helped me alot! Thanks! 

One thing I still haven't gotten working is the Unsubscribe. 

`context.Keybindings.Unsubscribe(mod, Keys.Space);`

The other stuff I managed to change, but that one just crashes for me.

**Comment by N1x0** [comment]
> 
> 
> That helped me alot! Thanks!
> 
> One thing I still haven't gotten working is the Unsubscribe.
> 
> `context.Keybindings.Unsubscribe(mod, Keys.Space);`
> 
> The other stuff I managed to change, but that one just crashes for me.

@TobiasDev  
 in case you hadn't figured this one out yet to fix your issue with `Unsubscribe` you just replace
`csharp context.Keybindings.Unsubscribe(mod, Keys.Space);`
with 
`csharp context.Keybinds.Unsubscribe(mod, Keys.Space);`
