### ISSUE TITLE
Crash with key not found in dictionnary

### ISSUE THREAD

**Issue by sim590** [workspacer/workspacer#119]
```
System.Collections.Generic.KeyNotFoundException: The given key '[5247074][C:\Users\sdesaulniers\Downloads\syncthing-windows-amd64-v1.6.1\syncthing-windows-amd64-v1.6.1\syncthing.exe][ConsoleWindowClass][conhost]' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at workspacer.WorkspaceManager.UpdateWindow(IWindow window, WindowUpdateType type)
```

This happened after I tried to `ALT+T` the CMD window for `syncthing.exe`. It seems to happen when there are many windows opened. I have like around 20 windows opened sometimes. Fortunately, I do have some rules for some windows so that they get routed else where when starting workspacer, but the programm still struggles with slow execution and crashes like the one I'm listing here.

**Comment by N1x0** [comment]
@sim590  Is this still an issue? Could you share your config file so I can have a look and see if there's anything related?

**Comment by sim590** [comment]
It has not happened since. I guess that #191 might have helped a bit since the _watcher_ can do his job and I'm not as often as earlier forced to replace all my windows. I can't say if it the bug is fixed for sure, but I have not gotten this issue since last update (I'm now on 0.9.10.32).

**Comment by N1x0** [comment]
@sim590  thanks for confirming, I will close this issue. Should you encounter the bug again do lrt me know and I'l reopen it.
