### ISSUE TITLE
How to Change Time and Date Formate in workspacer.Bar (TimeWidget)

### ISSUE THREAD

**Issue by MarvinMynx** [workspacer/workspacer#124]
I've found the responsible Code in your Project.
`public TimeWidget() : this(200, "hh:mm:ss tt") { }` on Line 22 in [TimeWidget.cs](https://github.com/rickbutton/workspacer/blob/master/src/workspacer.Bar/Widgets/TimeWidget.cs)
Is there a way to change this in the Config File workspacer.config.csx so I can have 24h format or even add the current date to the Time?

**Comment by N1x0** [comment]
for 24 hour time + date you can use the following:
`HH:mm dd/MM/yy` --> *18:00 04/09/20*

See` DateTime.ToString` Method for more information on formatting dateTime objects.

**Comment by HigeMynx** [comment]
Hmm now i get this Error message: Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (20,46): error CS0246: Der Typ- oder Namespacename "TimeWidget" wurde nicht gefunden (m÷glicherweise fehlt eine using-Direktive oder ein Assemblyverweis).

This is my Code:
```
	context.AddBar(new BarPluginConfig(){
		BarTitle = "workspacer.Bar",
		BarHeight = 40,
		FontSize = 10,
		FontName = "MesloLGS NF",
		RightWidgets = () => new IBarWidget[] {new TimeWidget(1000, "HH:mm  dd/MM/yy"), new ActiveLayoutWidget()},
	});
```

**Comment by HigeMynx** [comment]
Never mind, just needed to add `using workspacer.Bar.Widgets;` to my code.

**Comment by N1x0** [comment]
Closing this as formatting options are now explained in config.md
