### ISSUE TITLE
Can't close TextBlockMessage

### ISSUE THREAD

**Issue by BeeryShklar** [workspacer/workspacer#127]
When the keybinds window or an error window pops up there's no way to close it other than using a hotkey (for the keybinds menu) or killing the process from Task Manager.

This can probably be fixed by changing `false` at `workspacer.Share/TextBlockMessage.Designer.cs` line `68` to true.

**Comment by josteink** [comment]
Feel free to test, and if it works, send in a PR :)

**Comment by BeeryShklar** [comment]
@josteink I have tested it with the `keybinds` window and it works but I wasn't able to test it with the `error` window. Should I send a PR or wait for someone to test it?

**Comment by josteink** [comment]
Feel free! It's certainly better than nothing. 👍

**Comment by N1x0** [comment]
Just a quick question did you try maximising either window by double-clicking it the border? This should reveal the buttons at the bottom right, at least it does for me. Either way it's not a great situation so a fix would be great!

**Comment by N1x0** [comment]
Closing the issue as it was fixed in #191, tested and confirmed
