### ISSUE TITLE
Unresponsive PC when a new layout is added, followed by exceptionless crash

### ISSUE THREAD

**Issue by doctorshiban** [workspacer/workspacer#137]
Let me start by saying, workspacer is fantastic. I've been search and trying to find exactly this, but all other projects fall short. On to the issue -

I've written a new layout engine, compiled the app with dotnet 3.1, instantiated that engine in the config, but once I launch the built workspacer.exe, the PC becomes sluggish to the point of unresponsiveness (for 4-5 seconds) and then crashes without an exception message. I've tried to copy/paste one of the included layouts while changing the class names to make it unique, and the same thing happens

Removing it from the config makes workspacer work as expected

Thanks!

**Comment by N1x0** [comment]
Hi @doctorshiban , I could think of two reasons why this might happen based of the fact that you testing method of copy-pasting an existing `LayoutEngine` didn't work.

1.  There is an error in your config file
it should look something like this (I'm using sticky workspaces but that shouldn't matter):
```
var sticky = new StickyWorkspaceContainer(context, StickyWorkspaceIndexMode.Local);
context.WorkspaceContainer = sticky; 

sticky.CreateWorkspace("Vertical Layout", new VertLayoutEngine());
```
2. You ran the "wrong" workspacer.exe
If you have installed the release version and also compiled one yourself make sure that you run the right workspacer.exe file (depending on how you compiled it would be in 
 `Path to the source files\src\workspacer\bin\Debug\netcoreapp3.1\win-x64` 
or
 `Path to the sourcefiles\src\workspacer\bin\Release\netcoreapp3.1\win-x64` 

 The `LayoutEngines`  are stored in the `workspacer.shared.dll` file, so if you compile it from source that creates  a new .dll , but the release version still uses the "old" file. So if you have both a source-compiled and the github release version make sure you execute the right one. You could also just copy the newly created .dll to the existing installation folder (by default in `C:\Program Files\workspacer`) and overwrite the original.

I hope this helps, if it's neither of the two then a bit more digging might be needed though

**Comment by alashibangithub** [comment]
This seems to have been the issue (thanks for the patience)!
