### ISSUE TITLE
Monitors switch between workspaces when opening application

### ISSUE THREAD

**Issue by BeeryShklar** [workspacer/workspacer#159]
Sometimes when i open an application my 2 monitors switch workspaces, for example: `monitor 1` is on workspace `3` and `monitor 2` is on workspace`9`, I open an application and `monitor 1` is on workspace `9` and `monitor 2` is on workspace `3`.

I think this is a problem with the monitor array switching order which makes `monitor 1` `monitor 2` ext. but it's just speculation.

let me know if you need more data, I know this data isn't very useful unless you also have this problem but I don't really have more right now.

**Comment by N1x0** [comment]
Hi @BeeryShklar  is this still an issue on the current stable or unstable branch? I have trouble replicating so it may have been fixed on unstable so your feedback would be helpful.

If you want to test it yourself just change the branch in your config file.
```
config.Branch = Branch.Unstable
```
Also any particular programs where this happens more frequently or is it random?

**Comment by BeeryShklar** [comment]
I don't know. I have stopped using workspacer because of some of these problems and i'm currently on a trip so i can't test it.
It does seem like you are now on the right track to making workspacer better and I might come back to using it, it was just easier to not use any programs and just use the default windows' hotkeys.

**Comment by BeeryShklar** [comment]
@N1x0 I can confirm that this issue still is a problem. I have been using the newest version of workspacer (0.9.10) for only about 5 minutes and when I opened up a program (File Explorer) workspaces 1 and 2 switched monitors. I had Inskcape on workspace 1 (main monitor, 2k) and chrome on workspace 2 (secondary monitor, 1080p).

**Comment by dalyIsaac** [comment]
Could you post your config? It'd help with debugging.

**Comment by dalyIsaac** [comment]
I've now encountered the issue - I'll try figure out why this is happening.

**Comment by dalyIsaac** [comment]
@BeeryShklar would it be possible for you to test if #233 fixes this, if that's alright?
