### ISSUE TITLE
Custom default key binding error

### ISSUE THREAD

**Issue by projectoneuniverse** [workspacer/workspacer#173]
Thanks for developing thi, very useful.

How can i change the default key binding?
I tried with
`KeyModifiers mod = KeyModifiers.Alt;`
`context.Keybinds.Subscribe (mod, Keys.T, () => context.Keybinds.Subscribe (mod, Keys.I)); `
 
But an error message appears:
`Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (27,78): error CS1503: Argument 1: cannot convert from 'workspacer.KeyModifiers' to 'workspacer.MouseEvent'`

**Comment by N1x0** [comment]
What you're trying to do won't work like this  for two reasons

1. If you want to re-assign a default key you must first unsubscribe from the original with:
`context.Keybinds.Unsubscribe(mod, Keys.T);`
2. The keybind needs to have an *action* associated with it.
`context.Keybinds.Subscribe(mod, Keys.T, ()=> DO SOMETHING HERE);`

For example you could open a browser like so:
`context.Keybinds.Subscribe(mod, Keys.T, () => System.Diagnostics.Process.Start(@"C:\Program Files\Mozilla Firefox\firefox.exe"), "Browser");`
