### ISSUE TITLE
Fullscreen apps aren't in fullscreen

### ISSUE THREAD

**Issue by triplrrr** [workspacer/workspacer#187]
This is mainly referring to games that play in full screen. 

When I start a game or other fullscreen application, it is instead forced into borderless mode. Interestingly, this doesn't happen with applications like Mozilla Firefox while using youtube. This may be due to the difference in how fullscreen is handled there.

**Comment by system32uwu** [comment]
You can use filter to ignore them

// filters, workspacer will ignore windows with this names (I recommend ignoring games and fullscreen applications)
```c#
context.WindowRouter.AddFilter((window) => !window.Title.Contains("Getsu")); //Getsu Fuma Den
context.WindowRouter.AddFilter((window) => !window.Title.Contains("Lacuna")); //Lacuna context.WindowRouter.AddFilter((window) => !window.Title.Contains("Monster Train")); //Monster Train
```
