### ISSUE TITLE
How do I add gaps to workspacer?

### ISSUE THREAD

**Issue by Kawaiiaz** [workspacer/workspacer#192]
I want to add gaps to workspacer like there are in i3-gaps and other window manager. I do not see any keybinds or configuration that will allow me to have gaps? Can someone please help me?

**Comment by josteink** [comment]
There seems to be a PR for this, but it has yet to be merged:

https://github.com/rickbutton/workspacer/pull/161

**Comment by Kawaiiaz** [comment]
what about like config or something?

**Comment by dalyIsaac** [comment]
You could take a look at the PR #193.

**Comment by system32uwu** [comment]
#193 Was recently merged adding the option to add inner and outer gaps, you can see [dalylsaac's config file](https://github.com/dalyIsaac/workspacer-config/blob/main/workspacer.config.csx) that implements it. You can check the unstable release which should already have this (or else build from source and wait until the next stable release).

**Comment by dalyIsaac** [comment]
For example:

```csharp
#r "C:\Program Files\workspacer\plugins\workspacer.Gap\workspacer.Gap.dll"

using workspacer.Gap;

...

var gap = 20;
context.AddGap(
    new GapPluginConfig()
    {
        InnerGap = gap,
        OuterGap = gap / 2,
        Delta = gap / 2,
    }
);

```
