### ISSUE TITLE
Previous workspace in sticky workspaces goes to the wrong workspace

### ISSUE THREAD

**Issue by kmpi** [workspacer/workspacer#198]
In StickyContainers, previous workspace returns the wrong workspace, on a setup with 3 monitors, where there's 5 workspaces on each. Instead of looking at the number of workspaces on a monitor (5), it looks at the number of containers, which is 3, and uses that as an index. This results in the wrong workspace being chosen.

The fix is to change "_workspaces.Count" to "workspaces.Count" in "StickyWorkspaceContainer.cs" on line 174, this gives the correct workspace, as now it looks at the correct container, and not the private 'underscore' one, as far as I can see. I have tested the code and it fixes the issue for me.

Kind Regards

**Comment by N1x0** [comment]
Fixed by #199
