### ISSUE TITLE
System.Exception: you must specify at least enough workspaces to cover all monitors

### ISSUE THREAD

**Issue by adelin-b** [workspacer/workspacer#202]
I just installed workspacer and tryed to launch it, here is what happen.

I have 6 monitors on maybe its the problem

```
System.Exception: you must specify at least enough workspaces to cover all monitors
   at workspacer.workspacer.Start()
   at workspacer.Program.Run()
   at workspacer.Program.Main(String[] args)
```

**Comment by schiltz3** [comment]
Having at least 6 workspaces  in the config file located at: C:\Users\myUser\.workspacer\workspacer.config.csx  should fix the issue.

The line should look something like this once it is fixed:
context.WorkspaceContainer.CreateWorkspaces("1", "2", "3", "4","5","6","7");
