### ISSUE TITLE
Just fork it / Creating a community project

### ISSUE THREAD

**Issue by josteink** [workspacer/workspacer#211]
The current state of affairs seems to be that @rickbutton for the time being no longer has the interest or capacity to act as a maintainer for workspacer (for whatever reason, no judgement passed). 

To keep workspacer going forward I suggest creating a community fork, where new PRs can get integrated at a regular pace without building up merge conflicts. 

The obvious answer is probably to create a GitHub organisation where ownership can be delegated and passed on and organise the fork as a repo below that organisation. 

While I personally won’t contribute much code, I can setup the organisation and possibly also do some code review every now and then. 

What I need more is a list of people who wants access and possibly a list to their contributions to judge the merit of the claim. 

So… anyone who feel like taking workspacer a step further, please raise your hands!

**Comment by josteink** [comment]
As a side-note: creating a fork is easy. It’s maintaining it which is hard. 😋

I’m only interested in creating a fork if we can get a real community momentum with it, and I won’t go forward with it if people think it will negatively impact the community.

**Comment by schiltz3** [comment]
Truth 😄, I already have my own fork. I just know I can't possibly maintain the project. I'm still shaky on some of the concepts/language in the project.

**Comment by josteink** [comment]
Just name-dropping all current and past contributors, just to ensure nobody feels left out. :smile: 

CC: @sitiom @dalyIsaac @haoxiangliew @BeeryShklar @JCallicoat @N1x0 @MSylvia @OldKros @alex-griffiths @ahawker
@Zweihander-Main @wkpalan @NeoNlAmp3 @dlundgaard

**Comment by Fusion** [comment]
I am in a similar situation with another project. I understand the conundrum.
I suppose you contacted Rick directly and did not get a reply?

**Comment by josteink** [comment]
To be clear, I haven't contacted him about a possible fork, but I've sent emails in the past about the current state of PRs not getting merged, for which I've received no reply. 

Thus I didn't feel like emailing about a fork would be very fruitful either. 

But hey, I'm discussing this publicly on his projects issue-tracker, because I honestly believe it's for the good of the project, and if he has opinions he surely has the ability speak his mind. 

Hopefully this doesn't come of as me "betraying" him or anything 😂

**Comment by rickbutton** [comment]
Hi!

Apologies for the silence, I've been rather busy with professional and personal commitments for a long time that prevent me from working on workspacer, and haven't used it in some time. I 100% support community maintenance of the project, and will gladly help with the migration.

I already have the `workspacer` organization, in theory, I would just need to move the repo over to that organization, and add those who are interested as maintainers. Let's use this issue to discuss who is interested in that list, and making a list of to-dos for this.

**Comment by Fusion** [comment]
Organization is, IMO, definitely the way to go Rick.

**Comment by josteink** [comment]
> I already have the workspacer organization, in theory, I would just need to move the repo over to that organization

That's super easy. Github has a function to transfer ownership of a repo, and you can select your organization there. If you use that, all previous links (web, git, etc) to the repo on your personal account will automatically be redirected to the new repo owned by the organization.

I've done that in the past, and there has literally been zero issues.

**Comment by josteink** [comment]
If @rickbutton himself can setup the organization and aid the migration, I'm willing to act as a maintainer of sorts, doing code-review for incoming patches and stuff like that.

But me myself (not using Windows as my main OS anymore) won't be enough to drive this project, so hopefully someone else will want to step up too.

**Comment by system32uwu** [comment]
I would love to help enhance the docs and provide examples for configuration files, I'm pretty sure a lot of people didn't give workspacer a chance due to the lack of these (I was about to do it). We could also make a separated repository to add community plugins / modules to the bar like in [polybar-scripts](https://github.com/polybar/polybar-scripts), this may require some refactoring, otherwise we could just use APIs (like [Win32 API](https://docs.microsoft.com/en-us/windows/win32/api)) or powershell scripts and pipe the outputs to the UI.

**Comment by dalyIsaac** [comment]
I'd definitely be interested in contributing. 

However, I'd like to point out that [nog](https://github.com/TimUntersberger/nog) is a window manager in _active_ development which might be interesting to users of workspacer - you can find documentation at https://timuntersberger.github.io/nog/

I'm not sure what the feature parity of nog is compared to workspacer, though I do know of one limitation (https://github.com/TimUntersberger/nog/issues/273). However, it might be worth a look too.

cc @TimUntersberger

**Comment by TimUntersberger** [comment]
A few differences I found at first glance:

- Nog currently doesn't support automatic layouts.
- Nog uses lua instead of c#
- Nog doesn't support the windows key as a modifier
- Nog supports hot-reloading (https://github.com/TimUntersberger/nog/pull/277). I don't know whether workspacer supports hot-reloading.
- Nog supports gaps

I also want to add that I never looked at workspace before so I don't really have any idea what the differences are.

**Comment by josteink** [comment]
> Nog supports gaps

We have a PR for that, but it haven't been merged yet :laughing:

**Comment by dalyIsaac** [comment]
> That's super easy. Github has a function to transfer ownership of a repo, and you can select your organization there.

If this was done by @rickbutton, I'd be happy to contribute with patches and code-review. Like @schiltz3 I've been maintaining my own fork and attempting to contribute back upstream.

**Comment by N1x0** [comment]
Would be happy to be involved in the community project. I haven't been active recently as nothing really got merged so I would very much welcome it.

**Comment by josteink** [comment]
That's on overall a 100% positive response rate so far. I think it's worth a shot!

@rickbutton: could you press the buttons and make it happen? 🙂

**Comment by rickbutton** [comment]
I've transfered the repo to the workspacer organization, and added @josteink as an admin, and @dalyIsaac, @N1x0 as members interested in contributing. Please let me know if I've missed someone.

I think I've setup access correctly, let me know if I need to press more buttons.

**Comment by sitiom** [comment]
Great, all links should point to the workspacer organization now with #213.

**Comment by josteink** [comment]
Great! With all that settled, let’s get PRs merged! 😃

Now that we now have more contributors with write-access, should we keep the 2-review rule, or should we moderate it back to 1? Any opinions?

**Comment by dalyIsaac** [comment]
I'm not 100% confident in this repo yet so I'd be more comfortable with 2. However, I'd be perfectly happy with 1 if that's what we end up with.

**Comment by N1x0** [comment]
4 eyes are better than 2 ;)

**Comment by josteink** [comment]
Righto. I’ll keep things things as they are and keep an eye on the PRs. 

If they aren’t getting merged because of lack of reviews, I guess we can reconsider later. 

As for me, I’ve approved all PRs I’ve felt comfortable reviewing of those already there. 

If any of you other guys could do that too, we should be able to land 2-3-4 new fixes/features landed quite quickly.

**Comment by rickbutton** [comment]
Thanks y'all. Feel free to ping me on something to get my attention if more configuration buttons need pressed.

Very excited to see where the community takes workspacer :)

**Comment by josteink** [comment]
Great stuff everyone! 

Guess I’ll consider this issue 100% solved for now. Closing!
