### ISSUE TITLE
Allow window title bars to be removed

### ISSUE THREAD

**Issue by dalyIsaac** [workspacer/workspacer#217]
Provide an option for title bars to be removed (based on @lauverityhill's comment at https://github.com/workspacer/workspacer/issues/212#issuecomment-869144310)

![window with no title bar](https://user-images.githubusercontent.com/68158964/123542305-8f4bf080-d77b-11eb-9f61-b98b6a3ba796.png) 

https://github.com/workspacer/workspacer/issues/212#issuecomment-869242758 by @system32uwu 
> This can probably be done using the Win32 API, win3wm does this here

https://github.com/workspacer/workspacer/issues/212#issuecomment-869272380 by @dalyIsaac 
> nog has something similar - https://github.com/TimUntersberger/nog/blob/master/assets/default_config.lua
nog also has has_custom_titlebar which allows special handling for some executables.

https://github.com/workspacer/workspacer/issues/212#issuecomment-869289011 by @schiltz3 
> I played around with removing the Title Bar, and if someone does implement this. I would heavily recommend doing it in a way that supports special handling for some executables because messing with the GWL_STYLE is very inconsistent.

**Comment by pranavpa8788** [comment]
Has this worked for anyone on apps like Chrome, Windows terminal on Windows 11 for anyone?
