### ISSUE TITLE
Add a permanent focus border to the focussed window

### ISSUE THREAD

**Issue by egoexpress** [workspacer/workspacer#228]
As mentioned in #226 it would be helpful to have an option to see all the time which window is currently in focus. A permanent border with a configurable width and color would be nice for this.

The FocusIndicator which is currently used to indicate the focus of a window is controlled by a timer only and not suitable for this.

**Comment by tlsomers** [comment]
@josteink I believe this issue can now be closed 😅

**Comment by josteink** [comment]
Indeed!
