### ISSUE TITLE
Window management problems on Windows 11 (WSLg)

### ISSUE THREAD

**Issue by romanofski** [workspacer/workspacer#266]
I ran into trouble with running workspacer and running WSLg GUI apps:

![Screenshot (2)](https://user-images.githubusercontent.com/121047/137037885-ff071483-a96c-4115-819e-e3ae39a82661.png)

The problem is that:

a) The [wslg](https://github.com/microsoft/wslg) windows are not managed by workspacer. I'm not sure whether that is even possible. It seems as a workaround I can filter windows out based on title. Are there other attributes which can be used too?
b) The rendering is off too. As you can see in the screen shot, the Emacs contents are white, but will usually show some introduction text.

I'm not sure if I'm the only one who ran into this. I'd be interested if there are pointers to resources I can read in order to debug this issue any further.

PS: Thanks for this piece of software. I'm coming from XMonad on Linux and it's a real life saver.

**Comment by dalyIsaac** [comment]
> I did some digging, and it's in the road map for development.

For others, I think this is the relevant WSLg issue: https://github.com/microsoft/wslg/issues/22

**Comment by romanofski** [comment]
> I did some digging, and it's in the road map for development. I would say that it will be quite a long time, as the windowing system that they use, Weston + rdp, is particularly problematic, and unstable or unusable in many cases. If your main usage is emacs, then I recommend attaching it to a console 'emacs -nw' for the time being - if that suits your needs. Personally, I keep wslg triggered on or off depending on what I am doing at the time.

Yeah that is always a possibility. I'm not even using Wayland on Linux, but a Window Manager. The other alternative I had in mind was still running a full screen X server and a window manager from console. Perhaps the least integrated way of working tho.

> 
> You may also consider using gwsl, as it's still far more developed, or something hackier like manually sending an x11 window over rdp using the 'remote desktop' uwp client, since it supports resizing.

Thanks a lot for the pointer. I didn't even know it existed.

> Thanks btw, I had tried it in the w11 beta, and it was very problematic with my config. Set it up again yesterday, and it's wonderful - to say the least.

Glad it was of help.

**Comment by LGUG2Z** [comment]
I recently addressed this issue in `komorebi`, here is the relevant commit if you would like to apply the same logic/heuristic to `workspacer`: https://github.com/LGUG2Z/komorebi/commit/3f3c2815da5bf1f83a627c79915a4a4cff5c7ce9

**Comment by josteink** [comment]
Thanks @LGUG2Z!

If I understand that change correctly, it means that you match the process-name against a fixed list of names, and if there's a match on that, you don't consider other Windows-properties at all when deciding if the Window should be tiled or not (contrary to normal behaviour)

Is that correct?

If so, that should be fairly easy for someone to turn into a PR here as well :smiley:

**Comment by romanofski** [comment]
I had some time to try things out a bit. Well turns out Workspacer can be configured to ignore Window hints to solve this. The documentation mentions it under [Filters & Routes](https://workspacer.org/config/#filters--routes). I then could add the following configuration to ignore any program out of WSLg to get tiled:

```Csharp
context.WindowRouter.AddFilter((window) => !window.ProcessName.Contains("mstsc"));
```

However I noticed by using [VcXsrv](https://sourceforge.net/projects/vcxsrv/) and the window setup, it correctly decorates the WSL GUI apps with window hints which can be used by Windows and Workspacer. Perhaps for now the best way to move forward until WSLg provides the proper hinting.

Anyhow, thanks for all the help. Learned a lot. Since this is not a bug, I'll close it.

**Comment by azinsharaf** [comment]
@romanofski Can you please guid me how to configure Workspacer so WSL GUI applications running by VcXsrv get tiled?

**Comment by romanofski** [comment]
@azinsharaf for what it's worth replying so late. I think it must have something to do with existing windows and windows which are newly created. In some occasions "old" windows do not get picked up which is rare but I've seen it happen. I have not investigated further as to why that is the case.
