### ISSUE TITLE
Want to get rid of the top bar

### ISSUE THREAD

**Issue by Mesum-Hussain** [workspacer/workspacer#277]
I don't want a top bar on my screen which Workspacer provides and I don't even need the multiple desktops which comes with it. I am happy with the default desktops Windows 10 gives me and just wanted a tiling window manager functionality on top of it. How can I disable the top bar entirely?

**Comment by josteink** [comment]
I'm not sure that's a capability we have right now. Nobody has thought of using it just like that :smile: 

My advice is to take a look at the code and see what parts you don't feel you need, and see if:

* Workspacer can be configured to act like that, or
* Workspacer can be made to act like that by omitting parts of the initialization code

If first things work, good for you! Maybe help document it by updating the readme and issuing a PR?

If second trhing looks promising, report your findings and we can work on that.

Sounds like a plan?

**Comment by Mesum-Hussain** [comment]
Ok I will look into the source as soon as I get some time.

**Comment by Mesum-Hussain** [comment]
> I'm not sure that's a capability we have right now. Nobody has thought of using it just like that 😄
> 
> My advice is to take a look at the code and see what parts you don't feel you need, and see if:
> 
> * Workspacer can be configured to act like that, or
> * Workspacer can be made to act like that by omitting parts of the initialization code
> 
> If first things work, good for you! Maybe help document it by updating the readme and issuing a PR?
> 
> If second trhing looks promising, report your findings and we can work on that.
> 
> Sounds like a plan?

Ok I will look into the source code as soon as I get some time.

**Comment by N1x0** [comment]
If you don't want the top bar just remove `context.Addbar` from your config file.

**Comment by Mesum-Hussain** [comment]
> If you don't want the top bar just remove `context.Addbar` from your config file.

I am not sure where to find this config file you mentioned. Can you please guide me?

**Comment by josteink** [comment]
Right-click WorkSpacer tray-icon, create sample config? :smile:

**Comment by Mesum-Hussain** [comment]
> Right-click WorkSpacer tray-icon, create sample config? 😄

Thank you. That was very helpful. I was able to hide the status bar and get the apps full screen. But facing one more issue now on Windows11. Workspacer is treating the start menu and the search menu as a window, although start menu is not getting tiled but workspacer is leaving blank space as if it is tiled in that place. And the search menu is completely getting tiled among other windows. I am going to report it now. Thank you.
