### ISSUE TITLE
Workspacer is treating Windows11 Start Menu and Search Menu as an application window and trying to tile them.

### ISSUE THREAD

**Issue by Mesum-Hussain** [workspacer/workspacer#284]
On Windows11, Workspacer is treating the Start Menu as an application window and trying to tile it too. Although it is not getting tiled, but Workspacer is creating space for it among other tiled windows as if the start menu is tiled.
![Screenshot (7)](https://user-images.githubusercontent.com/64641670/152519154-450d3b8c-60e5-4458-8163-629131fc0eb1.png)
![Screenshot (8)](https://user-images.githubusercontent.com/64641670/152519187-c6f961ad-9389-4573-a891-f59cf9693902.png)
![Screenshot (9)](https://user-images.githubusercontent.com/64641670/152519204-a93a7c46-c890-4a7b-a3a7-d6b63dc9939f.png)

Same thing is happening with the search menu, and unfortunately it is getting tiled among other windows.
 
![Screenshot (10)](https://user-images.githubusercontent.com/64641670/152519372-ac4922f4-3b1c-4216-b0d6-e6056c8d4a0c.png)

**Comment by N1x0** [comment]
Same thing used to happen (#96 and #101) in Windows 10 until a process name filter was added by default. Should probably be done for this as well.  A quick google search says that the win11 start menu is called "StartMenuExperienceHost.exe", although I can't confirm this as I am still on Win10. While waiting for an official fix  you can just add the following lines to your config to avoid the behaviour:
```
context.WindowRouter.IgnoreProcessName("StartMenuExperienceHost.exe");
```

This should fix it.

**Comment by Mesum-Hussain** [comment]
> Same thing used to happen (#96 and #101) in Windows 10 until a process name filter was added by default. Should probably be done for this as well. A quick google search says that the win11 start menu is called "StartMenuExperienceHost.exe", although I can't confirm this as I am still on Win10. While waiting for an official fix you can just add the following lines to your config to avoid the behaviour:
> 
> ```
> context.WindowRouter.IgnoreProcessName("StartMenuExperienceHost.exe");
> ```
> 
> This should fix it.

I added that line but still there is no difference.

**Comment by Mesum-Hussain** [comment]
> > Same thing used to happen (#96 and #101) in Windows 10 until a process name filter was added by default. Should probably be done for this as well. A quick google search says that the win11 start menu is called "StartMenuExperienceHost.exe", although I can't confirm this as I am still on Win10. While waiting for an official fix you can just add the following lines to your config to avoid the behaviour:
> > 
> > ```
> > context.WindowRouter.IgnoreProcessName("StartMenuExperienceHost.exe");
> > ```
> > 
> > This should fix it.
> 
> I added that line but still there is no difference. 

It turns out that I need to add 

`context.WindowRouter.IgnoreProcessName("Search");
` 

Instead of

`context.WindowRouter.IgnoreProcessName("StartMenuExperienceHost.exe");
`

Now the problem is solved.

I will see if I can make a pull request with this line added soon.

Thanks 🙂

**Comment by josteink** [comment]
If you plan to fix this and make a PR for this, this is where we tried to fix this before:

https://github.com/workspacer/workspacer/commit/d0ae3cb11a37a6af73c2e68a7c21b1c7c5e8b1e8

**Comment by josteink** [comment]
Created PR here: https://github.com/workspacer/workspacer/pull/288
