### ISSUE TITLE
Sticky modifier keys when used with Plover Stenography

### ISSUE THREAD

**Issue by derekthecool** [workspacer/workspacer#286]
Wow, this really is wonderful project! I've recently started using Plover for all of my keyboard usage. [Plover](https://github.com/openstenoproject/plover) is an open source stenography program. It is very powerful and goes well with window manager programs like workspacer.

I'm having a very repeatable issue with modifier keys getting stuck after using Plover to change windows to change to next app. I'm using the default workspacer mappings.

When I use my command to do Alt+J or Alt+K which are mapped with a .json setup like this:
```json
{
  "STP-R": "{#alt(j)}",
  "STP-G": "{#alt(k)}"
}
```

Then afterwards my alt modifier is stuck. I see a similar behavior with windows key and shift. Control does not cause this problem if used by itself, but it does when used with other modifiers such as control + alt.

I've found the best quick fix to get the key modifiers unstuck is to click between different apps about 4-6 times. Then it will get reset.

I've spent a good deal of time finding that the source of this issue is from workspacer and not Plover. When workspacer is closed the modifier lock up does not occur.

I realize that I may be the only user who is using this at the moment, but I would love to help solve this. Stenography is a wonderful tool for power users!

I'm starting to search through the code to find a solution. But any pointers as to where I could start debugging the following things would be helpful:

* Logging keystrokes
* Looking at how the mouse events influence modifier state

**Comment by derekthecool** [comment]
Well, I have found the source of the issue.

With some debugging in the method KbdHook I can see that the key state of my modifiers such as alt do trigger with the 0x8000 high bit. But I can see that after I have done my modifier press, the state result from Win32.GetKeyState is 1.

```cs
short LAltState = Win32.GetKeyState(KeysToKeys(Keys.LMenu));
short RAltState = Win32.GetKeyState(KeysToKeys(Keys.RMenu));
```

According to the [Microsoft Website](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate#return-value)
If the low bit is set it implies that the key state is toggled.

```
Return value
Type: SHORT

The return value specifies the status of the specified virtual key, as follows:

If the high-order bit is 1, the key is down; otherwise, it is up.
If the low-order bit is 1, the key is toggled. A key, such as the CAPS LOCK key, is toggled if it is turned on. The key is off and untoggled if the low-order bit is 0. A toggle key's indicator light (if any) on the keyboard will be on when the key is toggled, and off when the key is untoggled.
```

I did not know that other keys such as alt could be toggled. But it makes sense in my case because the key presses are being sent from the Plover stenography software. So something about the simulated way those keys are being pressed and the way that workspacer is interacting with key states is causing this issue.


So my approach to solve this issue was to use the other windows API function [SetKeyState](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setkeyboardstate)

Which has the function definition of this:

```cpp
BOOL SetKeyboardState(
  [in] LPBYTE lpKeyState
);
```

So I tried setting up this function in the Win32.cs file like this:

```cs
        [DllImport("user32.dll")]
        public static extern bool SetKeyState(ref byte[] lpKeyState);
```

And then calling it at the end of the KeybindManager.cs method KbdHook like this:

```cs
                    if (key != Keys.None && modifiersPressed != KeyModifiers.None)
                    {
                        if (DoKeyboardEvent(key, modifiersPressed))
                        {
                            return new IntPtr(1);
                        }
                    }
                    else
                    {
                        Logger.Debug($"LAlt: {LAltState:X4}, RAlt: {RAltState:X4}");

                        byte[] ResetKeyStateArray = new byte[256];
                        for (int i = 0; i < ResetKeyStateArray.Length; i++)
                        {
                            ResetKeyStateArray[i] = 0;
                        }
                        try
                        {
                           bool result = Win32.SetKeyState(ref ResetKeyStateArray);
                        }
                        catch (Exception ex)
                        {
                            Logger.Error(ex, "Error using SetKeyState DLLimport function");
                        }
                    }
```

But I'm getting an exception about "No entry point to User32.DLL could be found" when I call the SetKeyState.

I know I have probably done something wrong with getting the lpbyte mapped properly. And I'm not even sure if this will using SetKeyState will solve my issue.
But I wanted to show my progress so far.


Any tips would be appreciated.

**Comment by derekthecool** [comment]
Okay, I found the source of my no entry error. I had named the function SetKeyState instead of SetKeyboardState.

But now that I've gotten past that error, and I am getting a proper call with a good return value still no luck.
I'm thinking now that either this function will not work for my purposes, or I'm setting the wrong values in my byte array.

**Comment by josteink** [comment]
Sorry. This is too low level Win32 juggling for my taste. Good digging so far though. Wish you the best of luck, and if you find a solution, a PR is definitely welcome. :smile:

**Comment by derekthecool** [comment]
Well after about 10 hours off testing and debugging I've found a very simple solution.

Use right alt instead of left alt. Why does this work? I still don't know! But it is no longer having mod keys getting stuck when using Plover!

But let me share one thing I found while testing different windows API calls.

I found that using SetKeyboardState was useless even when using GetKeyboardState so that I could more intelligently write values back. I also found that GetKeyboardState was about 10 times faster (0.3 ms) than using GetKeyState (3 ms).
This setup I have here shows how GetKeyboardState shows the same results as the GetKeyState as far as getting key state.


Win32.cs

```cs
        // https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setkeyboardstate
        [DllImport("user32.dll", SetLastError = true)]
        public static extern bool SetKeyboardState(byte[] lpKeyState);
```


KeybindManager.cs

```cs
        private IntPtr KbdHook(int nCode, UIntPtr wParam, IntPtr lParam)
        {
            if (nCode == 0 && ((uint)wParam == Win32.WM_KEYDOWN || (uint)wParam == Win32.WM_SYSKEYDOWN))
            {
                DateTime startTime = DateTime.Now;

                var key = (Keys)Marshal.ReadInt32(lParam);
                if (key != Keys.LShiftKey && key != Keys.RShiftKey &&
                    key != Keys.LMenu && key != Keys.RMenu &&
                    key != Keys.LControlKey && key != Keys.RControlKey &&
                    key != Keys.LWin && key != Keys.RWin)
                {
                    short LAltState = Win32.GetKeyState(KeysToKeys(Keys.LMenu));
                    short RAltState = Win32.GetKeyState(KeysToKeys(Keys.RMenu));
                    short LShiftState = Win32.GetKeyState(KeysToKeys(Keys.LShiftKey));
                    short RShiftState = Win32.GetKeyState(KeysToKeys(Keys.RShiftKey));
                    short LControlState = Win32.GetKeyState(KeysToKeys(Keys.LControlKey));
                    short RControlState = Win32.GetKeyState(KeysToKeys(Keys.RControlKey));
                    short RWinState = Win32.GetKeyState(KeysToKeys(Keys.RWin));
                    short LWinState = Win32.GetKeyState(KeysToKeys(Keys.LWin));

                    DateTime postGetKeyStateCalls = DateTime.Now;

                    byte[] FullKeyboardState = new byte[256];
                    bool GetKeyboardStateStatus = Win32.GetKeyboardState(FullKeyboardState);

                    if (GetKeyboardStateStatus)
                    {
                        Logger.Debug($"LAlt= From GetKeyState: 0x{LAltState:X} -- From GetKeyboardState: 0x{FullKeyboardState[(int)Keys.LMenu]:X}");
                        Logger.Debug($"RAlt= From GetKeyState: 0x{RAltState:X} -- From GetKeyboardState: 0x{FullKeyboardState[(int)Keys.RMenu]:X}");
                        Logger.Debug($"LShift= From GetKeyState: 0x{LShiftState:X} -- From GetKeyboardState: 0x{FullKeyboardState[(int)Keys.LShiftKey]:X}");
                        Logger.Debug($"RShift= From GetKeyState: 0x{RShiftState:X} -- From GetKeyboardState: 0x{FullKeyboardState[(int)Keys.RShiftKey]:X}");
                        Logger.Debug($"LControl= From GetKeyState: 0x{LControlState:X} -- From GetKeyboardState: 0x{FullKeyboardState[(int)Keys.LControlKey]:X}");
                        Logger.Debug($"RControl= From GetKeyState: 0x{RControlState:X} -- From GetKeyboardState: 0x{FullKeyboardState[(int)Keys.RControlKey]:X}");
                        Logger.Debug($"LWin= From GetKeyState: 0x{LWinState:X} -- From GetKeyboardState: 0x{FullKeyboardState[(int)Keys.LWin]:X}");
                        Logger.Debug($"RWin= From GetKeyState: 0x{RWinState:X} -- From GetKeyboardState: 0x{FullKeyboardState[(int)Keys.RWin]:X}");
                    }
                    else
                    {
                        Logger.Debug("GetKeyboardState failed!");
                    }

                    KeyModifiers modifiersPressed = 0;

                    // there is no other way to distinguish between left and right modifier keys
                    if ((LShiftState & 0x8000) == 0x8000)
                    {
                        modifiersPressed |= KeyModifiers.LShift;
                    }
                    if ((RShiftState & 0x8000) == 0x8000)
                    {
                        modifiersPressed |= KeyModifiers.RShift;
                    }
                    if ((LAltState & 0x8000) == 0x8000)
                    {
                        modifiersPressed |= KeyModifiers.LAlt;
                    }
                    if ((RAltState & 0x8000) == 0x8000)
                    {
                        modifiersPressed |= KeyModifiers.RAlt;
                    }
                    if ((LControlState & 0x8000) == 0x8000)
                    {
                        modifiersPressed |= KeyModifiers.LControl;
                    }
                    if ((RControlState & 0x8000) == 0x8000)
                    {
                        modifiersPressed |= KeyModifiers.RControl;
                    }
                    if ((LWinState & 0x8000) == 0x8000)
                    {
                        modifiersPressed |= KeyModifiers.LWin;
                    }
                    if ((RWinState & 0x8000) == 0x8000)
                    {
                        modifiersPressed |= KeyModifiers.RWin;
                    }

                    if (DoKeyboardEvent(key, modifiersPressed))
                    {
                        return new IntPtr(1);
                    }
                }
            }
            return Win32.CallNextHookEx(IntPtr.Zero, nCode, wParam, lParam);
        }
```

But there is one big problem with using this style. For some reason, when the GetKeyState calls are removed, the GetKeyboardState return does not properly show the state of modifiers. Again I'm not sure why is the case.



This has been a good experience to learn more about how workspacer works.
