### ISSUE TITLE
feat: add option to control bar transparency

### ISSUE THREAD

**Issue by amrbashir** [workspacer/workspacer#300]
I'd like to control the bar transparency, ideally through the `DefaultWidgetBackground` with something like this `new Color(0xff,0xff,0xff,0xBA)`.

I'd be happy to help but since I am not that good with winforms, I'd appreciate if you could just steer me in the right direction and I will try to help. I have some experience dealing with win32 apis btw.

**Comment by amrbashir** [comment]
Closing as I think this project seems unmaintained and I'd advise anyone to use https://github.com/LGUG2Z/komorebi since it works with the native windows taskbar pretty well and you can use https://github.com/TranslucentTB/TranslucentTB to control the taskbar color.

**Comment by josteink** [comment]
It's not entirely unmaintained, but it's not actively developed either. New features are the responsibility of those who want them, in form of PRs.

That said, komorebi looks nice too. Thanks for the suggestion!
