### ISSUE TITLE
can i change Alt key to FN key? 

### ISSUE THREAD

**Issue by azinsharaf** [workspacer/workspacer#319]
Hi,
Is it possible to change the ALT key to Function key (FN). so instead of ALT-1 I can use FN-1 (not F1).
The main reason is that I use ALT-left and Alt-right arrow to move between different panes in Windows Terminal.

**Comment by josteink** [comment]
I don't believe FN is a "real" key which is detectable by the OS, but instead a pseudo-key used by the keyboard FW to modify the key-press event sent to the OS, As such, this change is probably not doable.

Someone correct me if I'm wrong :)

**Comment by azinsharaf** [comment]
Hi, I ended up changing the Windows Terminal keybindings. Instead of FN key I used CTRL-H and CTRL-L to move the courser left and right between panes. 
I don't like that Workspacer is forcing to use arrow keys to move between spaces. . (as far as i know)
