### ISSUE TITLE
switch workspace using Alt -<letter>

### ISSUE THREAD

**Issue by azinsharaf** [workspacer/workspacer#336]
Hi, 
This is a question:
Instead of using ALT-number to switch between workspaces, is it possible to use letters? For instance instead of ALT-1 can we define ALT-E as the keymap? 
I have 5 workspaces (and one application for each) and using letters is easier to remember them. for instance ALT-O to switch the workspace for Outlook.

**Comment by inql** [comment]
If you apply config for workspacer, it should do the work:
```
IKeybindManager manager = context.Keybinds;
// removing all default keybinds
manager.UnsubscribeAll();
// or you can remove them one by with:
manager.Unsubscribe(KeyModifiers.LAlt, Keys.D1) // <- workspace 0
```
and reassign keybinds:
``` 
manager.Subscribe(KeyModifiers.LAlt, Keys.E, () => workspaces.SwitchToWorkspace(index), "switch to workspace index");
```
Of course you need to know index of the workspace that you want to assign.

Keys are available here:
https://github.com/workspacer/workspacer/blob/master/src/workspacer.Shared/Keybind/Keys.cs

**Comment by azinsharaf** [comment]
Thank you! That is exactly what i needed.
