### ISSUE TITLE
changing config file location?

### ISSUE THREAD

**Issue by azinsharaf** [workspacer/workspacer#342]
Hi, Is it possible to change the location of configuration file?
from `~/.workspacer/workspacer.config.csx` to `~/.config/workspacer/workspacer.config.csx`

**Comment by josteink** [comment]
Supporting both would be a small change, IMO.

Someone just have to decide which path takes precedence, and create a PR for it :smile:

**Comment by tlsomers** [comment]
This has now been implemented here:
https://github.com/workspacer/workspacer/pull/352.
