### ISSUE TITLE
FocusBorder persists during fullscreen

### ISSUE THREAD

**Issue by joanofstuff** [workspacer/workspacer#363]
It seems that the border drawn by the plugin stays visible while content (like a video) is fullscreened.
![image](https://user-images.githubusercontent.com/6023880/192126984-22734456-d680-4e7f-8f28-faf52be73fab.png)

**Comment by josteink** [comment]
I think this plugin was created by @tlsomers. Can you take a look this, please? :smile:

**Comment by tlsomers** [comment]
Sure, this pull request should fix this issue: https://github.com/workspacer/workspacer/pull/364
