### ISSUE TITLE
On restart, something went wrong and permanently hid some of my windows :(

### ISSUE THREAD

**Issue by scottopell** [workspacer/workspacer#37]
I used the tray icon to restart workspacer after a config change.

At this point some of my windows didn't come back, eg, I have two firefox windows and one of them came back and the other one didn't.

I had to restart my computer to fix this.

Two things could be done here:

1. A dedicated `fix-my-windows.exe` util outside of workspacer to show windows that workspacer touched
2. make sure the tray icon "restart" isn't doing something broken and weird

**Comment by rickbutton** [comment]
`0.9.4` had a bug where `workspacer.Watcher` was crashing on start, which causes this problem. `0.9.5 fixes this`.

(workspacer.Watcher is a process started by workspacer that specifically fixes your windows when workspacer quits or crashes)

**Comment by sim590** [comment]
This issue still happens to me. In particular, according to @rickbutton's explanation, it can happen if one kills the workspacer process tree, killing alsothe watcher. What to do then to recover your hidden windows which you know are still there somewhere?

**Comment by rickbutton** [comment]
This is a good point. `workspacer.Watcher` is attached to the main process and dies when the main process dies. Explicitly configuring the watcher to not do this should solve the problem. If `workspacer` dies unexpectedly, it should instead recover gracefully, and probably prompt to optionally restart workspacer.
