### ISSUE TITLE
Request - Public Workspacer Discord

### ISSUE THREAD

**Issue by Janthor** [workspacer/workspacer#372]
I've been thinking a lot on how Workspacer is currently the only tool that has a good level of customisation and quality for Tiling on Windows. But one thing that maybe is holding it back is community interaction. I feel like a public Discord would go a long way on having more developers collaborating on complex PR's, and also getting more user feedback on bugs/desired features.

If this is not something the main devs want, then no worries, i'll close this issue, but if it sounds interesting I'd be able to help on moderation / server setup.

**Comment by josteink** [comment]
I'm mostly just reviewing PRs at this point. I'm not actively developing anything, so I don't think I'm the main target for this issue.

I don't really "do" discord either. I prefer decentralized systems like Matrix or IRC, since I think that better aligns with the interests of an open-source project than a closed-source SaaS like Discord.

If anyone wants to set something up, as a community effort, I'm not against that though, and would be willing to link it in the readme, given that someone made the PR to add it.

**Comment by Nocxr** [comment]
I went ahead and made a matrix community: 

https://matrix.to/#/#workspacer-community:matrix.org
  
Right now its just 3 channels, general, snippets, and support.  I'm not sure of the amount of people who will join/use this but I figured Id make it.  I'm willing to hand off admin/moderation to someone else if they would like it at some point.  Hopefully this is ok and please let me know if anyone would like any changes to be made!

**Comment by jbrazio** [comment]
> I don't really "do" discord either. I prefer decentralized systems like [Matrix](https://matrix.org/) or IRC

Discord is the new IRC, everyone and it's dog uses it nowadays.. It's the first time I see a reference to "matrix.org".. in a nutshell, it would be far more accessible to the world to build a Discord guild.

**Comment by rickbutton** [comment]
big +1 for matrix over discord, I already use matrix daily, and its pretty great.

**Comment by josteink** [comment]
If the workspacer devs or maintainers use matrix, and none of them use discord... I guess hosting a community on discord would leave out some pretty important participants :smiley:

**Comment by jbrazio** [comment]
> I guess hosting a community on discord would leave out some pretty important participants

Guess we will never know that one.
As in life.. sometimes is not about what you have but about what you could gain.

🚀 Matrix it is.
I'm out of this discussion, cheers.

**Comment by rickbutton** [comment]
> Good for you. ;-)

yes, good for me, the original author of this project.

I don't particularly care if someone sets up a bridge, but wouldn't be interested in supporting it, just go to matrix instead, bridges are always flaky and unreliable.

closing this as it seems like we are good here
