### ISSUE TITLE
Windows with titlebar removed with TitleBar plugin break the layout

### ISSUE THREAD

**Issue by joanofstuff** [workspacer/workspacer#374]
Since the latest unstable release, windows with the titlebar removed with the TitleBar plugin break the layout. They are rendered incorrectly (the space occupied by the titlebar is still there, only empty instead of gone) and are impossible to move, breaking the layout whenever you try to move them.

Window rendered incorrectly (bottom right)
![image](https://user-images.githubusercontent.com/6023880/194621242-87a46ebc-c4e6-4720-b00d-826f0e8ce35c.png)

Empty space after moving top right window clockwise (you can see the other window is still showing behind it)
![image](https://user-images.githubusercontent.com/6023880/194621818-f7425dd2-3db6-4fb8-9ef0-553e122e7bac.png)
After the windows being like this, if you refocus the broken window and change to a different workspace, nothing happens.

Additionally, windows with their titlebar removed by other means (in this case, alacritty's own config) are unable to be managed with workspacer anymore, something that used to work before
![image](https://user-images.githubusercontent.com/6023880/194622149-01ffcf1d-cd24-437f-b5a1-a761df32d7d8.png)

**Comment by Janthor** [comment]
I feel like this is the same as #368 , which I proposed a fix on #373. Seems like current fullscreen detection is based on window style, which triggers false positives in windows that don't have a proper title bar.
