### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by ColonelBucket8** [workspacer/workspacer#386]
There's a dead link on this page https://github.com/workspacer/workspacer/wiki/Customization. When I click on this link [system32uwu's config](https://github.com/system32uwu/dotfiles/blob/main/windows10/.workspacer/workspacer.config.csx), I got 404 page not found
![image](https://user-images.githubusercontent.com/59568628/200095017-1b7c7489-7b86-426e-9797-39d8ce6644cf.png)

**Comment by josteink** [comment]
I guess errors in the wiki are best fixed in the wiki, not in the bug-tracker.

Is this something you could help out with, @system32uwu  ?

**Comment by ColonelBucket8** [comment]
HI @system32uwu, I think I can just refer to the documentation as you guys did a great job documented it.
