### ISSUE TITLE
Titlebar plugin

### ISSUE THREAD

**Issue by boogotti8** [workspacer/workspacer#405]
hi, i have setup config file from [dalyIsaac](https://github.com/dalyIsaac) but I cant add the Titlebar plugin.

Can some one help me as im not the best programmer?

**Comment by DWTW321** [comment]
The titlebar plugin is currently only available in the unstable release (ver. [0.9.12.141](https://github.com/workspacer/workspacer/releases/tag/unstable)).

**Comment by MartinAskestad** [comment]
This is how my TitleBarPlugin looks, the `#r` needs to be at the top, the rest in the `doConfig` function.
```csharp
#r "C:\Program Files\workspacer\plugins\workspacer.TitleBar\workspacer.TitleBar.dll"


var titleBarPluginConfig = new TitleBarPluginConfig();
titleBarPluginConfig.SetWindowProcessName("gvim", new TitleBarStyle(showTitleBar: false, showSizingBorder: false));
titleBarPluginConfig.SetWindowProcessName("WindowsTerminal", new TitleBarStyle(showTitleBar: false, showSizingBorder: false));
titleBarPluginConfig.SetWindowProcessName("neovide", new TitleBarStyle(showTitleBar: false, showSizingBorder: false));
context.AddTitleBar(titleBarPluginConfig);
```

**Comment by boogotti8** [comment]
Thanks will give this an go!

**Comment by josteink** [comment]
If this issue is solved, please consider closing the issue :smile:
