### ISSUE TITLE
Using LAlt and LControl as mod key ?

### ISSUE THREAD

**Issue by hector-rb** [workspacer/workspacer#408]
First of all I want to thank all the developers who make this magnificent TWM possible.

Could someone explain me how to configure Workspacer to use the Alt and Windows keys as a mod key?

Thanks in advance

**Comment by MartinAskestad** [comment]
Try this
```csharp
var altCtrl = KeyModifiers.LAlt | KeyModifiers.LControl;
binds.Subscribe(altCtrl, Keys.H, () => context.Workspaces.SwitchToPreviousWorkspace(), "Switch to previous workspace");

```

**Comment by hector-rb** [comment]
Hi Martin. Thanks for your message.

I start using Workspacer, but it seem that your suggestion allows to bind the 'switch to previous workspace' function to CtrlL+ AltL + H key combination.

However, I'm looking for a way to use the key combination CtrlL + AltL as mod key instead of the default Alt key.

**Comment by MartinAskestad** [comment]
I think I understand, have you tried this method?
https://github.com/workspacer/workspacer/blob/f981f23fa2ea5244a3741dbcd59b7e63a259af05/src/workspacer/Keybinds/KeybindManager.cs#L220

Perhaps if you do `context.Keybinds.SubscribeDefaults(KeyModifiers.LAlt | KeyModifiers.LControl);` you'll change the default mod key/keys.

**Comment by hector-rb** [comment]
Yes, I also try it. In this case I get an error message saying  (message translated from french language): 

<<'IKeybindManager' does not contain a definition for 'SubscribeDefaults' and no accessible 'SubscribeDefaults' extension method accepting a first argument of type 'IKeybindManager' was found (is a using directive or an assembly reference missing?)>>

**Comment by MartinAskestad** [comment]
Do you know which version of workspacer you are runnning?

**Comment by hector-rb** [comment]
Martin,

Today I downloaded the latets unestable version 0.9.12.145. 

I have the same error message. 

By the way, how can I check the running version  ?

**Comment by MartinAskestad** [comment]
Maybe the easiest solution is to copy the method SubscribeDefaults to your config and modify it to use the keys you want?

I installed workspacer using Scoop, and Scoop tells me the version I'm running. Don't think there is an about box for the program that says the version.

**Comment by hector-rb** [comment]
Thanks you for your suggestion. 

It is still interesting to know why 

context.Keybinds.SubscribeDefaults(KeyModifiers.LAlt | KeyModifiers.LControl)

does not work in this context.

Perhaps someone reading this post can have an answer.

**Comment by hector-rb** [comment]
I finally found the 'issue' #195 where a similar key binding is demanded and arm32x user gives the following code which works:

KeyModifiers mod = KeyModifiers.Win;
Type keybindManagerType = context.Keybinds.GetType();
var subscribeDefaultsMethod = keybindManagerType.GetMethod("SubscribeDefaults", new Type[] { typeof(KeyModifiers) });
if (subscribeDefaultsMethod != null) {
    context.Keybinds.UnsubscribeAll();
    subscribeDefaultsMethod.Invoke(context.Keybinds, new object[] { mod });
} else {
    Console.WriteLine("Could not change modifier key: SubscribeDefaults method not found.");
}
