### ISSUE TITLE
Update to a supported .NET runtime

### ISSUE THREAD

**Issue by jshield** [workspacer/workspacer#415]
Hey really love the core concept of workspacer, but unfortunately it appears to be running on the .NET 5 runtime which has been EOL for the past 9 months, what is your roadmap for moving to a currently supported .NET runtime? 

I would like to get this whitelisted where I work but it has been flagged as being unmaintained due to using an obsolete and potentially dangerous framework.

**Comment by josteink** [comment]
Upgrading shouldn't be too hard. Pretty much flicking a switch at this point.

But ofcourse someone has to do the grunt-work. PRs welcome :smile:

**Comment by josteink** [comment]
PR sent here: https://github.com/workspacer/workspacer/pull/419

**Comment by josteink** [comment]
Released in unstable. And closed, I guess?
