### ISSUE TITLE
no config file generated?

### ISSUE THREAD

**Issue by reDpz** [workspacer/workspacer#434]
I dont think a config file generated, can someone just send me theirs or tell me how to generate it?
![image](https://user-images.githubusercontent.com/71374038/232608112-4705d730-bd4f-4159-b3e1-842b51f8b139.png)

**Comment by jshield** [comment]
https://github.com/workspacer/workspacer/blob/master/src/workspacer/Config/workspacer.config.template.csx

**Comment by jshield** [comment]
reading the wiki is also advisable

**Comment by reDpz** [comment]
hi, it made the .workspacer file on its own in %userprofile%.

I tried copying in another users config because thats the only way I knew how to and it seems to responding to the config so I'm currently working on figuring out all the binds.

Are the colors not as customiseable as dwm? are there patches i need to apply?

**Comment by josteink** [comment]
> hi, it made the .workspacer file on its own in %userprofile%.

That's not it.

Like @jshield  says you need to create a `..workspacer` directory inside `%userprofile%`. And that directory you need to create the config file, and name it `workspacer.config.csx`.

**Comment by josteink** [comment]
There's this whole webpage here which might serve as a good reference:

https://workspacer.org/config/

**Comment by josteink** [comment]
Also for reference, here are the default keybindings: https://workspacer.org/keybindings/

**Comment by Aareon** [comment]
Closing as solved!
