### ISSUE TITLE
"Sticky" Layouts

### ISSUE THREAD

**Issue by ianelletson** [workspacer/workspacer#60]
Use-case: I have a vertical monitor which should default to a different layout engine than my horizontal monitors. If I have a workspace open on my horizontal monitor and move it to my vertical monitor, its layout should update automatically, and vice-versa.

**Comment by rickbutton** [comment]
Interesting! I had not considered this as an idea before. I will investigate whether this is feasible.

**Comment by ianelletson** [comment]
Just an FYI, but I don't _expect_ you to do any of the issues I added! I may end up submitting a PR for them down the road.

**Comment by spadino** [comment]
I just thought the same. I also have a dual monitor setup, with the monitor on my left positioned vertical. It's almost the same height as the main monitor. I consider the ide to automatically switch the layout whenever "move" a tag to the vertical monitor quite a fantastic idea!
