### ISSUE TITLE
Window gap configuration

### ISSUE THREAD

**Issue by pauloday** [workspacer/workspacer#95]
Is there a way to configure the window gap? I'd like the windows to touch each other directly. If not, any tips on how I might go about adding such an option? I'm pretty sure I could add it, but I haven't got much of a chance to dig through the code yet. Thanks!

**Comment by rickbutton** [comment]
You should actually be able to do this experimentally without touching the source of workspacer at all. if you implement the `workspacer.Shared.ILayoutEngine` interface, you can override the layout engine used, and you are free to implement gaps in such an implementation.

I would LOVE for this to exist, so if you feel like trying it out feel free to create a PR! This should totally exist as a builtin.

**Comment by sitiom** [comment]
Resolved by #193.
